from enum import Enum, EnumMeta


class MyEnumMeta(EnumMeta):
    def __contains__(cls, item):
        return item in cls.__members__.values()


class MyEnum(Enum, metaclass=MyEnumMeta):
    """enum"""

    @property
    def idx(self):  # no index, which maybe overrided by subclass
        return list(self.__class__).index(self)


class IntEnum(int, MyEnum):
    """int enum"""


class StrEnum(str, MyEnum):
    """str enum"""

    def __str__(self):
        return self.value

    def __repr__(self) -> str:
        return repr(self.value)


class FileType(StrEnum):
    Unknown = "unknown"
    WORD = "word"
    PPT = "ppt"
    EXCEL = "excel"
    PDF = "pdf"
    SNIP = "snip"


class Direction(IntEnum):
    # PIL.Image.Transpose
    Unknown = -2  # 未进行设置
    Normal = -1
    # Flip_LR = 0
    # Flip_TB = 1
    Rotate_90 = 2  # 逆时针旋转90度
    Rotate_180 = 3  # 逆时针旋转180度
    Rotate_270 = 4  # 逆时针旋转270度 （顺时针90度）


class TableBBoxType(IntEnum):
    Table = 0
    Column = 1
    Row = 2
    Header = 3
    Cell = 4
    Content = 5


# fmt: off
class ParseMode(IntEnum):
    DumpHosting = -3           # 禁用解析，输出原始图像数据至image hosting server
    DumpLocal = -2             # 禁用解析，输出原始图像数据至本地
    DumpBase64 = -1            # 禁用解析，输出原始图像数据至base64编码
    Disable = 0                # 禁用解析，禁用输出
    OCRFast = 1                # 快速OCR，默认设置
    OCRHighQuality = 2         # 高质OCR，【暂不支持】


class ParseModeTextual(IntEnum):
    DumpHosting = -3           # 禁用解析，输出原始图像数据至image hosting server
    DumpLocal = -2             # 禁用解析，输出原始图像数据至本地
    DumpBase64 = -1            # 禁用解析，输出原始图像数据至base64编码
    Disable = 0                # 禁用解析，禁用输出
    OCRFast = 1                # 快速OCR，默认设置
    OCRHighQuality = 2         # 高质OCR，支持行内公式
    DigitalExported = 3        # 数字原生，直接复制PDF文本（有概率字符错误）


class OrderingMethod(StrEnum):
    Naive = "naive"             # 简单排序
    GapTree = "gap_tree"        # Gap Tree算法
    XYCut = "xy_cut"            # XYCut算法
    XYCutExp = "xy_cut_exp"     # XYCut算法-扩展版


class Language(StrEnum):
    """
    Enum class for language, generated by langcodes & fasttext
    https://www.ruanyifeng.com/blog/2008/02/codes_for_language_names.html
    https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes
    https://www.loc.gov/standards/iso639-2/php/code_list.php
    https://en.wikipedia.org/wiki/ISO_639:a
    """

    Unknown = "unknown"                # 未知

    Afrikaans = "af"                   # 南非荷兰语
    Tosk_Albanian = "als"              # Tosk Albanian
    Amharic = "am"                     # 阿姆哈拉语
    Aragonese = "an"                   # 阿拉贡语
    Arabic = "ar"                      # 阿拉伯语
    Egyptian_Arabic = "arz"            # Egyptian Arabic
    Assamese = "as"                    # 阿萨姆语
    Asturian = "ast"                   # 阿斯图里亚斯语
    Avaric = "av"                      # 阿瓦尔语
    Azerbaijani = "az"                 # 阿塞拜疆语
    South_Azerbaijani = "azb"          # South Azerbaijani
    Bashkir = "ba"                     # 巴什基尔语
    Bavarian = "bar"                   # Bavarian
    Central_Bikol = "bcl"              # Central Bikol
    Belarusian = "be"                  # 白俄罗斯语
    Bulgarian = "bg"                   # 保加利亚语
    Bihari_languages = "bh"            # Bihari languages
    Bangla = "bn"                      # 孟加拉语
    Tibetan = "bo"                     # 藏语
    Bishnupriya = "bpy"                # Bishnupriya
    Breton = "br"                      # 布列塔尼语
    Bosnian = "bs"                     # 波斯尼亚语
    Russia_Buriat = "bxr"              # Russia Buriat
    Catalan = "ca"                     # 加泰罗尼亚语
    Chavacano = "cbk"                  # Chavacano
    Chechen = "ce"                     # 车臣语
    Cebuano = "ceb"                    # 宿务语
    Central_Kurdish = "ckb"            # 中库尔德语
    Corsican = "co"                    # 科西嘉语
    Czech = "cs"                       # 捷克语
    Chuvash = "cv"                     # 楚瓦什语
    Welsh = "cy"                       # 威尔士语
    Danish = "da"                      # 丹麦语
    German = "de"                      # 德语
    Dimli_individual_language = "diq"  # Dimli (individual language)
    Lower_Sorbian = "dsb"              # 下索布语
    Dotyali = "dty"                    # Dotyali
    Divehi = "dv"                      # 迪维希语
    Greek = "el"                       # 希腊语
    English = "en"                     # 英语
    Esperanto = "eo"                   # 世界语
    Spanish = "es"                     # 西班牙语
    Estonian = "et"                    # 爱沙尼亚语
    Basque = "eu"                      # 巴斯克语
    Persian = "fa"                     # 波斯语
    Finnish = "fi"                     # 芬兰语
    French = "fr"                      # 法语
    Northern_Frisian = "frr"           # 北弗里西亚语
    Western_Frisian = "fy"             # 西弗里西亚语
    Irish = "ga"                       # 爱尔兰语
    Scottish_Gaelic = "gd"             # 苏格兰盖尔语
    Galician = "gl"                    # 加利西亚语
    Guarani = "gn"                     # 瓜拉尼语
    Goan_Konkani = "gom"               # Goan Konkani
    Gujarati = "gu"                    # 古吉拉特语
    Manx = "gv"                        # 马恩语
    Hebrew = "he"                      # 希伯来语
    Hindi = "hi"                       # 印地语
    Fiji_Hindi = "hif"                 # Fiji Hindi
    Croatian = "hr"                    # 克罗地亚语
    Upper_Sorbian = "hsb"              # 上索布语
    Haitian_Creole = "ht"              # 海地克里奥尔语
    Hungarian = "hu"                   # 匈牙利语
    Armenian = "hy"                    # 亚美尼亚语
    Interlingua = "ia"                 # 国际语
    Indonesian = "id"                  # 印度尼西亚语
    Interlingue = "ie"                 # 国际文字（E）
    Iloko = "ilo"                      # 伊洛卡诺语
    Ido = "io"                         # 伊多语
    Icelandic = "is"                   # 冰岛语
    Italian = "it"                     # 意大利语
    Japanese = "ja"                    # 日语
    Lojban = "jbo"                     # 逻辑语
    Javanese = "jv"                    # 爪哇语
    Georgian = "ka"                    # 格鲁吉亚语
    Kazakh = "kk"                      # 哈萨克语
    Khmer = "km"                       # 高棉语
    Kannada = "kn"                     # 卡纳达语
    Korean = "ko"                      # 韩语
    Karachay_Balkar = "krc"            # 卡拉恰伊巴尔卡尔语
    Kurdish = "ku"                     # 库尔德语
    Komi = "kv"                        # 科米语
    Cornish = "kw"                     # 康沃尔语
    Kyrgyz = "ky"                      # 柯尔克孜语
    Latin = "la"                       # 拉丁语
    Luxembourgish = "lb"               # 卢森堡语
    Lezghian = "lez"                   # 列兹金语
    Limburgish = "li"                  # 林堡语
    Lombard = "lmo"                    # Lombard
    Lao = "lo"                         # 老挝语
    Northern_Luri = "lrc"              # 北卢尔语
    Lithuanian = "lt"                  # 立陶宛语
    Latvian = "lv"                     # 拉脱维亚语
    Maithili = "mai"                   # 迈蒂利语
    Malagasy = "mg"                    # 马拉加斯语
    Eastern_Mari = "mhr"               # Eastern Mari
    Minangkabau = "min"                # 米南佳保语
    Macedonian = "mk"                  # 马其顿语
    Malayalam = "ml"                   # 马拉雅拉姆语
    Mongolian = "mn"                   # 蒙古语
    Marathi = "mr"                     # 马拉地语
    Western_Mari = "mrj"               # Western Mari
    Malay = "ms"                       # 马来语
    Maltese = "mt"                     # 马耳他语
    Mirandese = "mwl"                  # 米兰德斯语
    Burmese = "my"                     # 缅甸语
    Erzya = "myv"                      # 厄尔兹亚语
    Mazanderani = "mzn"                # 马赞德兰语
    Nahuatl_languages = "nah"          # Nahuatl languages
    Neapolitan = "nap"                 # 那不勒斯语
    Low_German = "nds"                 # 低地德语
    Nepali = "ne"                      # 尼泊尔语
    Newari = "new"                     # 尼瓦尔语
    Dutch = "nl"                       # 荷兰语
    Norwegian_Nynorsk = "nn"           # 挪威尼诺斯克语
    Norwegian = "no"                   # 挪威语
    Occitan = "oc"                     # 奥克语
    Odia = "or"                        # 奥里亚语
    Ossetic = "os"                     # 奥塞梯语
    Punjabi = "pa"                     # 旁遮普语
    Pampanga = "pam"                   # 邦板牙语
    Palatine_German = "pfl"            # Palatine German
    Polish = "pl"                      # 波兰语
    Piedmontese = "pms"                # Piedmontese
    Western_Panjabi = "pnb"            # Western Panjabi
    Pashto = "ps"                      # 普什图语
    Portuguese = "pt"                  # 葡萄牙语
    Quechua = "qu"                     # 克丘亚语
    Romansh = "rm"                     # 罗曼什语
    Romanian = "ro"                    # 罗马尼亚语
    Russian = "ru"                     # 俄语
    Rusyn = "rue"                      # Rusyn
    Sanskrit = "sa"                    # 梵语
    Yakut = "sah"                      # 萨哈语
    Sardinian = "sc"                   # 萨丁语
    Sicilian = "scn"                   # 西西里语
    Scots = "sco"                      # 苏格兰语
    Sindhi = "sd"                      # 信德语
    Serbian_Latin = "sh"               # 塞尔维亚语（拉丁文）
    Sinhala = "si"                     # 僧伽罗语
    Slovak = "sk"                      # 斯洛伐克语
    Slovenian = "sl"                   # 斯洛文尼亚语
    Somali = "so"                      # 索马里语
    Albanian = "sq"                    # 阿尔巴尼亚语
    Serbian = "sr"                     # 塞尔维亚语
    Sundanese = "su"                   # 巽他语
    Swedish = "sv"                     # 瑞典语
    Swahili = "sw"                     # 斯瓦希里语
    Tamil = "ta"                       # 泰米尔语
    Telugu = "te"                      # 泰卢固语
    Tajik = "tg"                       # 塔吉克语
    Thai = "th"                        # 泰语
    Turkmen = "tk"                     # 土库曼语
    Filipino = "tl"                    # 菲律宾语
    Turkish = "tr"                     # 土耳其语
    Tatar = "tt"                       # 鞑靼语
    Tuvinian = "tyv"                   # 图瓦语
    Uyghur = "ug"                      # 维吾尔语
    Ukrainian = "uk"                   # 乌克兰语
    Urdu = "ur"                        # 乌尔都语
    Uzbek = "uz"                       # 乌兹别克语
    Venetian = "vec"                   # 威尼斯语
    Veps = "vep"                       # 维普森语
    Vietnamese = "vi"                  # 越南语
    West_Flemish = "vls"               # West Flemish
    Volapük = "vo"                     # 沃拉普克语
    Walloon = "wa"                     # 瓦隆语
    Waray = "war"                      # 瓦瑞语
    Wu_Chinese = "wuu"                 # 吴语
    Kalmyk = "xal"                     # 卡尔梅克语
    Mingrelian = "xmf"                 # Mingrelian
    Yiddish = "yi"                     # 意第绪语
    Yoruba = "yo"                      # 约鲁巴语
    Cantonese = "zh-yue"               # 粤语
    Chinese_Simplified = "zh-hans"     # 中文简体
    Chinese_Traditional = "zh-hant"    # 中文繁体


class StatusFlag(StrEnum):
    Undefined = "undefined"          # 未定义, 下载/接收文件中
    Waiting = "waiting"              # 等待中, 文件信息初始化中
    Processing = "processing"        # 处理中, 逐页处理中
    Success = "success"              # 成功, 文件处理完成
    Error = "error"                  # 失败, 文件处理出错


class FormatFlag(StrEnum):
    Empty = "empty"                  # 空, 无内容
    Plain = "plain"                  # 普通文本, 无前后缀
    Markup = "markup"                # 标记文本, 有前后缀
    Markdown = "markdown"            # Markdown
    Latex = "latex"                  # LaTeX
    Html = "html"                    # HTML


class ErrorFlag(StrEnum):
    OS_Error = "OS Error"                          # 系统错误
    Request_Required = "Request is required"       # 请求缺失
    Request_Invalid = "Request is invalid"         # 请求错误
    Token_Required = "Token is required"           # 需要给定token
    Token_Invalid = "Token is invalid"             # token包含非法字符
    Token_Duplicated = "Token is duplicated"       # token已存在
    File_Required = "File is required"             # 需要给定文件流
    File_Not_Found = "File not found"              # 文件不存在
    File_Invalid = "File is invalid"               # PDF文件无效/页数为0
    URL_Required = "URL is required"               # 需要给定URL
    Snip_Required = "Snippet is required"          # 需要给定文本片段
    Snip_Not_Found = "Snippet not found"           # 文本片段不存在
    Snip_Invalid = "Snippet is invalid"            # 文本片段无效
    URL_Invalid = "URL is invalid"                 # URL未指向有效PDF文件
    Status_Not_Found = "Status not found"          # 解析状态不存在
    Status_Decode_Failed = "Status decode failed"  # 解析状态解码失败
    Result_Not_Found = "Result not found"          # 解析结果不存在
    Result_Decode_Failed = "Result decode failed"  # 解析结果解码失败
    Lang_Unknown = "Lang is unknown"               # 无法判定语言
    Lang_Not_Supported = "Lang is not supported"   # 语言不支持OCR
    Pages_Required = "Page list is required"       # 未选择解析页
    Process_Failed = "Process failed"              # 解析失败


class LayoutType(StrEnum):
    """
    Enum class for layout type [from YOLO]
    """

    # abstract layout
    Section = "section"           # 章节书签
    Page = "page"                 # 页面
    # UNI-v0 only
    Description = "description"   # 表格/图标等注解
    # UNI-v1 only
    Text = "text"                 # 文本
    Figure = "figure"             # 图片
    # UNI-v0 & UNI-v2
    Legend = "legend"             # 图例
    Token = "token"               # 索引标记
    Paragraph = "paragraph"       # 段落
    Equation = "equation"         # 数学公式
    # UNI-v0 & UNI-v1 & UNI-v2
    Title = "title"               # 标题
    Caption = "caption"           # 图片/表格标题
    Molecule = "molecule"         # 分子
    Table = "table"               # 表格
    Chart = "chart"               # 图表
    Expression = "expression"     # 化学反应式

    # new version
    DocumentTitle = "documenttitle"   # 文档标题
    KeyValue = "keyvalue"             # 键值对 / 字段代码（专利）
    Reference = "reference"           # 参考文献
    Code = "code"                     # 代码
    TOC = "toc"                       # 目录
    Image = "image"                   # 图像
    ImageCaption = "imagecaption"     # 图像标题
    ImageFootnote = "imagefootnote"   # 图像脚注
    TableFootnote = "tablefootnote"   # 表格脚注
    EquationID = "equationid"         # 公式编号
    MoleculeID = "moleculeid"         # 内联分子索引
    
    PageHeader = "pageheader"  # 页眉
    PageFooter = "pagefooter"  # 页脚
    PageNumber = "pagenumber"  # 页码
    PageBar = "pagebar"        # 页栏
    PageNote = "pagenote"      # 页注
    Watermark = "watermark"    # 水印（其他）

    # supplementary
    HLine = "hline"                    # 水平分割线
    Group = "group"                    # 组合
    Abandon = "abandon"                # 丢弃
    Tabular = "tabular"                # 表单/列表型文本，需Tab信息
    List = "list"                      # 列表，包括有序/无序
    EquationInline = "equationinline"  # 内联公式

    # SYN model
    Identifier = "identifier"     # 分子标记的序号

    # fine-grained
    TableCaption = "tablecaption"             # 表格标题
    FigureCaption = "figurecaption"           # 图片标题
    ExpressionCaption = "expressioncaption"   # 化学反应式标题
    
    TableGroup = "tablegroup"                 # 表格组
    FigureGroup = "figuregroup"               # 图片组
    MoleculeGroup = "moleculegroup"           # 分子组
    ExpressionGroup = "expressiongroup"       # 化学反应式组
    
    Continued = "continued"                   # 续表/续图/续分子/续公式


class LayoutTypeBot(StrEnum):
    DocumentTitle = LayoutType.DocumentTitle
    Title = LayoutType.Title
    Paragraph = LayoutType.Paragraph
    KeyValue = LayoutType.KeyValue
    Reference = LayoutType.Reference
    Table = LayoutType.Table
    TableCaption = LayoutType.TableCaption
    TableFootnote = LayoutType.TableFootnote
    Image = LayoutType.Image
    ImageCaption = LayoutType.ImageCaption
    ImageFootnote = LayoutType.ImageFootnote
    Equation = LayoutType.Equation
    EquationID = LayoutType.EquationID
    Code = LayoutType.Code
    TOC = LayoutType.TOC
    Group = LayoutType.Group
    HLine = LayoutType.HLine
    PageHeader = LayoutType.PageHeader
    PageFooter = LayoutType.PageFooter
    PageNumber = LayoutType.PageNumber
    PageBar = LayoutType.PageBar
    PageNote = LayoutType.PageNote
    Watermark = LayoutType.Watermark


class LayoutTypeTop(StrEnum):
    Molecule = LayoutType.Molecule
    MoleculeID = LayoutType.MoleculeID
    MoleculeGroup = LayoutType.MoleculeGroup
    Figure = LayoutType.Figure
    Expression = LayoutType.Expression
    Chart = LayoutType.Chart
    Legend = LayoutType.Legend
    FigureCaption = LayoutType.FigureCaption
    FigureGroup = LayoutType.FigureGroup
    EquationInline = LayoutType.EquationInline
    

class SemanticType(StrEnum):
    # textual
    Textual = "textual"         # 文本类
    # group
    Table = "table"             # 表格
    Expression = "expression"   # 化学反应式
    # entity
    Molecule = "molecule"       # 分子
    Chart = "chart"             # 图表
    Figure = "figure"           # 图片
    Equation = "equation"       # 数学公式
    # ignore
    Ignore = "ignore"           # 忽略


TextualTypes = [
    LayoutType.Title,
    LayoutType.DocumentTitle,
    LayoutType.Caption,
    LayoutType.Paragraph,
    LayoutType.Text,
    LayoutType.Legend,
    LayoutType.Token,
    LayoutType.Description,
    LayoutType.Tabular,
    LayoutType.List,
    LayoutType.Identifier,
    LayoutType.EquationID,
    LayoutType.MoleculeID,
    LayoutType.Code,
    LayoutType.TOC,
    LayoutType.PageHeader,
    LayoutType.PageFooter,
    LayoutType.PageNumber,
    LayoutType.PageBar,
    LayoutType.PageNote,
    LayoutType.KeyValue,
    LayoutType.Reference,
    LayoutType.ImageCaption,
    LayoutType.ImageFootnote,
    LayoutType.TableCaption,
    LayoutType.TableFootnote,
    LayoutType.FigureCaption,
    LayoutType.ExpressionCaption,
]

EntityTypes = [
    LayoutType.Molecule,
    LayoutType.Chart,
    LayoutType.Figure,
    LayoutType.Equation,
    LayoutType.EquationInline,
]

GroupedTypes = [
    LayoutType.Table,
    LayoutType.Expression,
    LayoutType.Image,
]

IgnoreTypes = [
    LayoutType.Abandon,
    LayoutType.Watermark,
]

FunctionalTypes = [
    LayoutType.Section,
    LayoutType.HLine,
    LayoutType.Group,
    LayoutType.TableGroup,
    LayoutType.FigureGroup,
    LayoutType.ExpressionGroup,
    LayoutType.MoleculeGroup,
    LayoutType.Continued,
]
# fmt: on

# convert to ppocr abbr
PPOCR_LANG = {
    Language.Chinese_Simplified: "ch",
    Language.Chinese_Traditional: "chinese_cht",
    Language.Japanese: "japan",
    Language.Korean: "korean",
    Language.English: "en",
    Language.Russian: "ru",
    Language.French: "fr",
    Language.German: "german",
    Language.Hungarian: "hu",
    Language.Norwegian: "no",
    Language.Danish: "da",
    Language.Portuguese: "pt",
    Language.Polish: "pl",
    Language.Swedish: "sv",
    Language.Spanish: "es",
    Language.Serbian: "rs_latin",
    Language.Latin: "rs_latin",
}

SUPPORTED_LANG = list(PPOCR_LANG.keys())


def to_semantic(layout_type: LayoutType):
    if layout_type in TextualTypes:
        return SemanticType.Textual
    elif layout_type in [LayoutType.Image, LayoutType.Figure]:
        return SemanticType.Figure
    elif layout_type in IgnoreTypes:
        return SemanticType.Ignore
    elif layout_type in FunctionalTypes:
        return SemanticType.Ignore
    elif layout_type in [LayoutType.Equation, LayoutType.EquationInline]:
        return SemanticType.Equation
    else:
        return SemanticType[layout_type.name]


if __name__ == "__main__":
    print(Language.Chinese_Simplified)
    print([Language.Chinese_Simplified])
    print({Language.Chinese_Simplified: "chinese"})

    assert Language.Chinese_Simplified in ["zh-hans"]  # str mixin
    assert Language.Chinese_Simplified in {"zh-hans": 1}  # str mixin
    assert LayoutType.Title == "title"
    assert LayoutType("title") == LayoutType.Title
    assert OrderingMethod("gap_tree") == OrderingMethod.GapTree
    assert "zh-hans" in list(Language)
    assert Language.Chinese_Simplified in list(Language)
    assert Language("zh-hans") == Language.Chinese_Simplified
    assert Language["Chinese_Simplified"] == Language.Chinese_Simplified
    assert TableBBoxType(0) == TableBBoxType.Table
    assert "xy_cut" in list(OrderingMethod)
    assert "xy_cut" in OrderingMethod

    assert set(map(to_semantic, LayoutType)) == set(SemanticType)
    N = len(TextualTypes) + len(EntityTypes) + len(GroupedTypes) + len(IgnoreTypes) + len(FunctionalTypes)
    assert N == len(LayoutType), f"{N} != {len(LayoutType)}"
    assert set(TextualTypes + EntityTypes + GroupedTypes + IgnoreTypes + FunctionalTypes) == set(LayoutType), "overlap"

    print(LayoutType.Title.idx)
    print(list(LayoutType))
    print(ParseMode(False), ParseMode(True), ParseMode(2))
    print(min(ParseMode.Disable, ParseMode.OCRFast, ParseMode.OCRHighQuality))
    print(bool(ParseMode.Disable), bool(ParseMode.OCRFast), bool(ParseMode.OCRHighQuality))
